### PR TITLE
 💵 Add some new currencies #1613

### PR DESCRIPTION
**Pull request by ithiame**

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]

**Comment by Tirodem** [comment]
I have some huge doubts about results : ❌ 

image
image

image
image

image
image

image
image

image
image

image
image

image
image

For previous currencies, we're more or less OK (marging related to our exchange rate API) :
image
image

image
image

**Comment by coyotte508** [comment]
ah yes @ithiame need to make sure this is valid:

```

			const resp = await fetch('https://api.coinbase.com/v2/exchange-rates?currency=BTC', {
				...{ autoSelectFamily: true }
			} as unknown as RequestInit);
```

from `currency-lock`

**Comment by ithiame** [comment]
I have good results on my test

Config currencies
image

pricetag
image

image

image

image

**Comment by coyotte508** [comment]
you can both check `exchangeRate` in `RuntimeConfig` - see if it's updated

**Comment by ithiame** [comment]
image

**Comment by coyotte508** [comment]
Seems good!

Maybe @Tirodem there are multiple processed on the same DB and there was a lock in place, so the currencies didn't update?

(otherwise, deploy again & wait a few minutes. Or run locally)

**Comment by Tirodem** [comment]
I see the records on runtimeConfig, I gonna deploy it again.
Are the datas from src/lib/stores/exchangeRate.ts used at the beginning before we request the exchange API for fresh rates and stock them in runtimeConfig ?
What's the frequency of this call ?

**Comment by Tirodem** [comment]
Amounts are good now.

**Pull request merged**
