### PR TITLE
Manage decimals on price #1461

### PR DESCRIPTION
**Pull request by ithiame**

### CODE REVIEW

**Comment by coyotte508** [comment]
I think the main problem in https://github.com/B2Bitcoin/beBOP/issues/1461 is that we already have `FRACTION_DIGITS: 2` but we display `5.9` instead of `5.90`

This PR doesn't solve that.

IMO we can start with:

- If there are decimals, display them (min 2, max `FRACTION_DIGITS`)
- If there are not decimals, don't display them

Then if we encounter a specific client that has specific needs (or a specific currency) we can adapt

**Comment by Tirodem** [comment]
image
image
image
image
I don't see the change :(

**Comment by Tirodem** [comment]
> I think the main problem in #1461 is that we already have `FRACTION_DIGITS: 2` but we display `5.9 €` instead of `5.90 €`
> 
> This PR doesn't solve that.
> 
> IMO we can start with:
> 
> * If there are decimals, display them (min 2, max `FRACTION_DIGITS`)
> * If there are no decimals, don't display them
> 
> Then if we encounter a specific client that has specific needs (or a specific currency) we can adapt the codebase with a more involved solution

yes, that's the target issue, 5.6€ should be 5.60€, while 5€ should stay 5€, but 0.02133BTC should stay 0.02133BTC and 123545 SATS should stay 123545 SATS

**Review by coyotte508 — APPROVED** [review]

**Comment by coyotte508** [comment]
and @ithiame the other problem is for BTC, we don't want to display 8 fraction digits if I input `1.27` as @Tirodem explained

**Review by coyotte508 — APPROVED** [review]

**Pull request merged**
