### PR TITLE
Change header theme style management on mobile view #1249

### PR DESCRIPTION
**Pull request by ithiame**
📱 Change header theme style management on mobile view #1249

### CODE REVIEW

**Review by coyotte508 — COMMENTED** [review]
ok to merge if @Tirodem oks it

For PRs like this please include screenshots

**Comment by Tirodem** [comment]
Requested class header & navbar are missing.
Please do next commit with printscreen, and check UI behavior before.

**Comment by ithiame** [comment]
After :

**Comment by Tirodem** [comment]
Fine for me
image

**Review by coyotte508 — APPROVED** [review]

**Pull request merged**
