### PR TITLE
replace logo be-bop - change beBop to be-Bop in code

### PR DESCRIPTION
**Pull request by ithiame**

### CODE REVIEW

**Comment by coyotte508** [comment]
please just replace the existing files (both of them), no need to create a separate file or update the paths

also the logo you uploaded is the one for light mode not dark mode I think. For the dark mode one  you can replace the dark blue by white.

**Comment by coyotte508** [comment]
The colors are inverted 
image

**Comment by ithiame** [comment]
the light is most visible in dark vice-versa that's why i inverted it ?

**Comment by ithiame** [comment]
Corrected it !

**Review by coyotte508 — APPROVED** [review]
Thanks

**Pull request merged**
