### PR TITLE
✨ Paypal integration

### PR DESCRIPTION
**Pull request by coyotte508**
When paypal is configured:

- The "card" payment method becomes available (SumUp and Stripe have priority if they're also configured). **Guest checkout** should be enabled in the paypal settings so users do not have to create a paypal account
- The "paypal" payment method becomes available

On payment, the client is redirected to paypal's page. Paypal doesn't offer a widget for paypal payments, at least not that I could easily find.

### CODE REVIEW

**Comment by Tirodem** [comment]
"Secret" input should be secret
(same for Phoenixd http password, now I think about it)

**Comment by Tirodem** [comment]
Would it be possible, on /admin/paypal, to test connexion with filled credentials through a "Test connexion" CTA, and display a "succesfully connected" / "there was an error" message in return ?

**Comment by coyotte508** [comment]
> "Secret" input should be secret (same for Phoenixd http password, now I think about it)

do you mean it should be like a password input, with "***" ?

**Comment by Tirodem** [comment]
Yeah.
In fact I'm not sure we should display the password / secret key / whatever from be-BOP admin UI but it's a deeper thought we'll have later (as usually people knowing credential infos will take them from paypal / sum up / etc and put them in be-BOP, no one really need to take the information from be-BOP as they can fetch it again on payment processor backoffices).

**Comment by coyotte508** [comment]
can we open a separate issue maybe, as it touches sumup/stripe/phoenix/paypal?

**Comment by Tirodem** [comment]
BTW, Paypal goes from 0.01$ to 4000$, 5000$ or more for each transaction, depending of the seller account status.
I think, in order to display dynamically Paypal on a checkout, we should do something like this :
image
It can be done in a round 2 but, in that case, we must implement a hard maximum treshold (like the minimum treshold for Bitcoin that is currently implemented) and set it to the minimum of the "maximum amounts for a transaction" on paypal's side.

**Comment by Tirodem** [comment]
BTW, it's a like detail, but before implementing a SVG, is it possible to change icon from 💸 to 🅿 for payment mean ? (on /admin/order for example)

**Comment by coyotte508** [comment]
> BTW, it's a like detail, but before implementing a SVG, is it possible to change icon from 💸 to 🅿 for payment mean ? (on /admin/order for example)

yes

**Comment by coyotte508** [comment]
> BTW, Paypal goes from 0.01$ to 4000$, 5000$ or more for each transaction, depending of the seller account status. I think, in order to display dynamically Paypal on a checkout, we should do something like this : (...)

> It can be done in a round 2 but, in that case, we must implement a hard maximum treshold (like the minimum treshold for Bitcoin that is currently implemented) and set it to the minimum of the "maximum amounts for a transaction" on paypal's side.

`MIN_SATOSHIS_FOR_BITCOIN_PAYMENT` is only used on the frontend, no checks in the backend :see_no_evil: 

Can we merge as is? I'll do a quick PR afterwards to add the payment methods minimum/maximum amounts in `admin/config` in the "Payment methods" section

**Comment by Tirodem** [comment]
We can merge, I review it, and we'll see later for improvements (but let's not them waste on an iceberg).

**Review by Tirodem — APPROVED** [review]

**Pull request merged**
