### PR TITLE
 Free cart cannot be ordered (anymore ?) #1193

### PR DESCRIPTION
**Pull request by ithiame**

### CODE REVIEW

**Comment by Tirodem** [comment]
Functional feedbacks (seen on workshop thread) :
❌ no sent notification (because of no payment created ?)
☢️ "nothing to pay (free cart)" is available if I have a free product + a paying product (so, a non-free cart)
🔬 as we're creating no payment the order has no receipt, that can be a problem in... "some cases"

Note that this ticket allowed me to find this :
https://github.com/B2Bitcoin/beBOP/issues/1196

**Review by coyotte508 — COMMENTED** [review]
Can you test if it still works if we change the payment methods through the UI in `/admin/config`?

It should still allow to do free payments

**Comment by ithiame** [comment]
> Can you test if it still works if we change the payment methods through the UI in `/admin/config`?
> 
> It should still allow to do free payments
It still works

**Comment by coyotte508** [comment]
you can try to find why the tests are failing, otherwise I'll look into it later

**Review by coyotte508 — APPROVED** [review]
Seems good for me

If functional ok, then :+1:

**Comment by Tirodem** [comment]
That point is fixed :
☢️ "nothing to pay (free cart)" is available if I have a free product + a paying product (so, a non-free cart)

For the last points :

🔬 as we're creating no payment the order has no receipt, that can be a problem in... "some cases"
That can wait for a bit (as it's OK in the native, law compliant, invoice behavior of beBOP).

❌ no sent notification (because of no payment created ?)
That one is more annoying to me (that's why I expected a "free payment" payment mean, I supposed that the payment was the trigger to the notifications).

Still, we have fixed the free price UX issue, and if there's an issue (loss of order URL), the customer can buy it for free again, so I'll go merge for now.
And create tickets for the future for these two points.

**Comment by coyotte508** [comment]
It's possible to add a payment "free" in the payments and mark it as paid cc @ithiame

like a regular payment

**Pull request merged**
