### PR TITLE
Pos product addition error

### PR DESCRIPTION
**Pull request by ithiame**

### CODE REVIEW

**Review by coyotte508 — COMMENTED** [review]
Just do `alert(errorMessage);`

Let's not add components and what not just to handle an error message in one specific case.

**Comment by ithiame** [comment]
I tried to do as specified on the issue.

But if alert is ok it's easier

**Comment by coyotte508** [comment]
ah my bad - we can go back to the popup but then we need a more generic approach - up to you @Tirodem

**Comment by Tirodem** [comment]
@coyotte508 It's good as it is, I'll merge like this if it's OK with you and I'll do a ticket later with a more clean long-term perspective for the new required component for popin.

**Review by coyotte508 — APPROVED** [review]

**Pull request merged**
