### PR TITLE
Ignore width, contain and likely options on mobile for [Picture=] #1325

### PR DESCRIPTION
**Pull request by ithiame**

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]
More correct term is "hide the instructions"

**Comment by Tirodem** [comment]
In fact, it wasn't "hide the instructions", it was really "don't apply [Picture=] parameters on mobile device.
Thread opened on discord, to discuss monday.
BTW, you can display instructions again (or if we don't do the original request, we can throw this PR).

**Comment by coyotte508** [comment]
up to you @Tirodem to approve

**Comment by ithiame** [comment]
Before
image

After
image

**Comment by Tirodem** [comment]
Ok now parameters for Picture aren't applying anymore to mobile display.
But they don't apply anymore to desktop version... ❌ 
You can check it on https://dev-bootik.pvh-labs.ch/ homepage (it's still deployed)

**Comment by ithiame** [comment]
Desktop :
image

Mobile:
image

**Pull request merged**
