### PR TITLE
Change preorder product date information on /admin/product/{id} #1222

### PR DESCRIPTION
**Pull request by ithiame**
🦋 Change preorder product date information on /admin/product/{id} #1222

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]
Make sure to test this thoroughly in order to ensure it doesn't remove the available date of preorders in some scenario

**Comment by Tirodem** [comment]
> Make sure to test this thoroughly in order to ensure it doesn't remove the available date of preorders in some scenario

That point is OK but the initial point of the issue is KO.
When I replace my preorder date
image
by nothing :
image
and I save, here's what I have :
image
Initial goal of the issue is to fix that, I don't understand the diff of the PR as the empty value is not saved.

**Comment by ithiame** [comment]
It should save an empty date and make the product available. Are you sure  there's no change ?

**Comment by Tirodem** [comment]
My bad, deploy error.
Is OK after recheck ✅

**Pull request merged**
