### PR TITLE
Nostr PWYW

### PR DESCRIPTION
**Pull request by coyotte508**

### CODE REVIEW

**Comment by Tirodem** [comment]
1/ nostr-cart and real order cart aren't sync, real cart is made with initial PWYW price
image
image

2/ add to cart confirmation message must be changed to take the set amount
image

**Comment by coyotte508** [comment]
3/ seems impossible given the code, we explictly do `			if (product.payWhatYouWant) {` first

**Comment by coyotte508** [comment]
1/ and 2/ should be fixed - the cart was created with real data, the problem happened when converting it to an order

**Comment by Tirodem** [comment]
Indeed, 3 is good, test data issue.

2 is also good.

And so is 1 👏

**Review by Tirodem — APPROVED** [review]

**Pull request merged**
