### PR TITLE
Adapt custom CTA on product page to content + limit content input

### PR DESCRIPTION
**Pull request by ithiame**

### CODE REVIEW

**Review by coyotte508 — APPROVED** [review]

**Comment by Tirodem** [comment]
Chain breaking is not done
image
:x:

**Comment by Tirodem** [comment]
Too brutal ❌ 
Here's my fill :
`dans ma valise il y a carlos et un sac de nougats`
Here's my CTA :
image
Ok, chain is broken, but there's no reason to put a break between "s" and "ac" on "sac".
We need a smarter way of breaking chains.

**Comment by Tirodem** [comment]
And there's no character limit on input :
image

**Comment by ithiame** [comment]
Before:
image

After:
image

**Pull request merged**
